---
# Daniel Wolosiuk
# dw4102@rit.edu
# Oct 17 2025
- name: Deploy Daniel Wolosiuk's red team tool
  hosts: all
  become: yes
  tasks:
    - name: Deploy binary from dist/bad_ls to the target system
      shell:


  # install util-linux for wall